export type TInitDataItem = [
  id: number,
  CName: string,
  CDate: string,
  RDate: string,
  CDem: number,
  RDem: number,
  CZen: number,
  RZen: number,
  CBak: number,
  RBak: number,
  CKli: number,
  RKli: number,
  CTotal: number,
  RTotal: number,
  Comments: string,
  Approved: boolean,
  Details: string,
  Notes: string,
];
